language: go
sudo: required
install: true
go:
  - 1.7.3
env:
  global:
    - GOARCH=amd64
    - GO_FOR_RELEASE=1.7.3
before_install:
  - sleep 15
  - sudo apt-get install -y
  - go env && pwd
script:
  - make build
