sudo: false
language: go

os:
        - linux

env:
        - ARCH=x86_64

go:
        - 1.6.2

before_install:
        - apt-get -qq update
        - apt-get install -y lxc 

script:
        - make build
        - make install
