---
# This .yml runs tests against the dedicated openebs setup

##########################################################################################
- hosts: localhost
  tasks:
    - slack: 
        token: "{{ lookup('env','SLACK_TOKEN') }}" 
        msg: "{{ ansible_date_time.time }} OPENEBS TESTSUITE: STARTED"
      when: slack_notify | bool and lookup('env','SLACK_TOKEN')
###########################################################################################
# TC NAME: test-fio
# TC DETAILS: Runs fio with a basic rw workload profile on the storage from a container
# TC NOTES:  
#    a) Volume properties can be set in ./roles/volume/defaults/main.yml 
#    b) fio run duration can be set in ./roles/fio/defaults/main.yml
# 
#- include: playbooks/dedicated/test-fio/fio-prerequisites.yml
#
#- include: playbooks/dedicated/test-fio/fio.yml
#
#- include: playbooks/dedicated/test-fio/fio-cleanup.yml
#  when: clean | bool
#
###########################################################################################
# TC NAME: test-k8s-mysql-pod
# TC DETAILS: Deploys mysql pod on a k8s cluster with storage provisioned by flexvol driver
# TC NOTES:           
#
- include: playbooks/dedicated/test-k8s-mysql-pod/k8s-mysql-pod.yml
#
###########################################################################################
# TC NAME: test-k8s-percona-mysql-pod
# TC DETAILS: Deploys percona pod on k8s cluster with storage provisioned by flexvol driver
# TC NOTES:           
#    
- include: playbooks/dedicated/test-k8s-percona-mysql-pod/k8s-percona-pod.yml
#
###########################################################################################
- hosts: localhost
  tasks:
    - slack: 
        token: "{{ lookup('env','SLACK_TOKEN') }}" 
        msg: "{{ ansible_date_time.time }} OPENEBS TESTSUITE: ENDED"
      when: slack_notify | bool and lookup('env','SLACK_TOKEN')
###########################################################################################
