---
- hosts: localhost
  roles:
    - {role: k8s-localhost, when: build_type == "normal"} 

- hosts: kubernetes-kubemasters
  roles:
    - k8s-master

- hosts: kubernetes-kubeminions
  roles: 
    - k8s-hosts   
