# Define a new api (configuration) - openebs.io/v1aplha1
# Include the details on how storage will be allocated for the replicas
# The options can include:
# - host-directory-path 
# - lvm using local or remote disks (connected via iscsi/fc/nbd)
# Will also contain details on how to use:
# - cache from nvme disks
# - backup storage from S3
# The above configuration can be specified at a cluster level or
# per node (minion) 

# The storage-manager(s) will look for updates on this spec 
# and take the appropriate actions. 

# This file will also specify the different storage tiers
# that will be used to associate with storage-classes
# For example:
# - A node can have an lvm out of SSD disks or with a remote
#   disk. The local ssd disks will be used for high-performance
#   persistentvolumeclaims, where as remote disks can be used 
#   for backup-jobs persistentvolumeclaims. 

