---
- name: Delete jupyter server pod 
  shell: source ~/.profile; kubectl delete -f {{ pod_yaml_alias }}
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"

- name: Confirm jupyter pod has been deleted
  shell: source ~/.profile; kubectl get pods
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  register: result
  until: "'jupyter' not in result.stdout"
  delay: 120 
  retries: 6


   
