---
## K8S-LOCALHOST PREPARATION

- name: Install APT Packages
  apt: 
    name: "{{item}}"
    state: present
  with_items: "{{deb_local_packages}}"
  become: true
  delegate_to: 127.0.0.1
  tags: install_apt_packages

- name: Install PIP Packages
  pip:
    name: "{{ item }}"
    state: present
  with_items: "{{ pip_local_packages }}"
  become: true
  delegate_to: 127.0.0.1 
  tags: install_pip_packages

## KUBERNETES ROLE PREPARATION

- name: Get .deb kubernetes packages google cloud 
  get_url: 
    url: "{{ item }}"
    dest: "{{ playbook_dir }}/roles/kubernetes/files"
    force: yes
  register: result
  until:  "'OK' in result.msg"
  delay: 5
  retries: 3
  with_items: "{{ K8s_deb_packages }}"
  become: true
  tags: get_deb_packages 

- name: Fetch K8s images from gcr.io/google_containers
  docker_image: 
    name: "{{item}}"
    state: present
    pull: true
    force: yes
  register: result
  until: "'Pulled image {{ item }}' in  result.actions"
  delay: 60
  retries: 3  
  with_items: "{{ K8s_images }}"
  become: true
  tags: fetch_K8s_images

- name: Print K8s image names
  shell: printf "{{ item }}\n" >> imagelist.tmp
  with_items: "{{ K8s_images }}"
  tags: list_K8s_images

- name: TAR the K8s images 
  shell: sudo docker save $(cat imagelist.tmp) -o k8s_images.tar
  tags: tar_K8s_images

- name: Remove the .tmp file created to hold image list
  file: path="{{playbook_dir}}/imagelist.tmp" state=absent
  tags: remove_tmp_files

- name: Move K8s_images.tar into kubernetes role
  shell: mv {{playbook_dir}}/k8s_images.tar {{ playbook_dir }}/roles/kubernetes/files
  tags: move_K8s_images.tar

- name: Remove K8s images from K8s-localhost
  docker_image:
    name: "{{ item }}" 
    state: absent
  with_items: "{{ K8s_images }}"
  become: true
  tags: remove_K8s_images 

- name: Fetch the weave .yaml template from GitHub
  get_url:
    url: "{{ weave_template_link }}"
    dest: "{{ playbook_dir }}/roles/kubernetes/templates"
    force: yes
  register: result
  until:  "'OK' in result.msg"
  delay: 5
  retries: 3
  become: true
  tags: fetch_weave_template

## K8S-MASTER ROLE PREPARATION

- name: Fetch configure_K8s scripts into k8s-master role
  get_url: 
    url: "{{ item }}"
    dest: "{{ playbook_dir }}/roles/k8s-master/files"
    force: yes
  register: result
  until:  "'OK' in result.msg"
  delay: 5
  retries: 3 
  with_items: "{{ k8s_master_scripts }}"
  become: true
  tags: fetch_k8s_master_scripts

- name: Fetch weave images from dockerhub
  docker_image:
    name: "{{ item }}"
    state: present
    pull: true
    force: yes
  register: result
  until: "'Pulled image {{ item }}' in  result.actions"
  delay: 60
  retries: 3
  with_items: "{{ weave_images }}" 
  become: true
  tags: fetch_weave_images

- name: Print weave image names
  shell: printf "{{ item }}\n" >> imagelist.tmp
  with_items: "{{ weave_images }}"
  tags: list_weave_images

- name: TAR the weave images
  shell: sudo docker save $(cat imagelist.tmp) -o weave_images.tar
  tags: tar_weave_images

- name: Remove the .tmp file created to hold image list
  file: path="{{playbook_dir}}/imagelist.tmp" state=absent
  tags: remove_tmp_files

- name: Move weave_images.tar into k8s-master role
  shell: mv {{playbook_dir}}/weave_images.tar {{ playbook_dir }}/roles/k8s-master/files
  tags: move_weave_images.tar

- name: Remove weave images from K8s-localhost
  docker_image:
    name: "{{ item }}" 
    state: absent
  with_items: "{{ weave_images }}"
  become: true
  tags: remove_weave_images 

## K8S-HOSTS ROLE PREPARATION

- name: Fetch configure_K8s scripts into k8s-host role
  get_url:
    url: "{{ item }}"
    dest: "{{ playbook_dir }}/roles/k8s-hosts/files"
    force: yes
  register: result
  until:  "'OK' in result.msg"
  delay: 5
  retries: 3 
  with_items: "{{ k8s_host_scripts }}"
  become: true
  tags: fetch_k8s_hosts_scripts
  
  

  
