- name: Install subversion on K8S-master
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ deb_packages }}"
  become: true 
  delegate_to: "{{ groups['kubernetes-kubemasters'].0 }}"

      
