- hosts: localhost
 
  vars_files: 
    - k8s-crunchy-pg-vars.yml 
 
  tasks:

    - name: Get $HOME of K8s master for kubernetes user
      shell: source ~/.profile; echo $HOME
      args: 
        executable: /bin/bash
      register: result_kube_home
      delegate_to: "{{groups['kubernetes-kubemasters'].0}}"

    - name: Check whether maya-apiserver pod is deployed
      shell: source ~/.profile; kubectl get pods | grep maya-apiserver
      args: 
        executable: /bin/bash
      register: result
      delegate_to: "{{groups['kubernetes-kubemasters'].0}}"     

    - name: 
      debug: 
        msg: "Ending play, maya-apiserver is not running"
      when: "'Running' not in result.stdout"

    - name: 
      meta: end_play
      when: "'Running' not in result.stdout"

    - name: Replace 'tree/master' with 'trunk' in the crunchy-postgres link
      debug:
        msg={{ crunchy_pg_git_dir | regex_replace('tree/master', 'trunk')}}
      register: git_svn_link

    - name: Set the modified link as a fact
      set_fact:
        crunchy_dir: "{{ git_svn_link.msg }}"
      
    - name: Download the crunch-postgres folder kubemaster home
      subversion:
        repo: "{{ crunchy_dir }}"
        export: yes
        dest: "{{ result_kube_home.stdout }}/crunchy-postgres"
      delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
 
    - name: Replace volume size in set.json
      lineinfile:
        path: "{{ result_kube_home.stdout }}/crunchy-postgres/set.json"
        regexp: "\"storage\":"
        line: "              \"storage\": \"{{postgres_vol_size}}\""
      delegate_to: "{{groups['kubernetes-kubemasters'].0}}"

    - name: Comment the cleanup step in the run.sh  
      lineinfile:
        path: "{{ result_kube_home.stdout }}/crunchy-postgres/run.sh" 
        regexp: 'cleanup.sh'
        line: '#$DIR/cleanup.sh'
        backup: yes
      delegate_to: "{{groups['kubernetes-kubemasters'].0}}"

    - name: Run the shell script to setup postgres cluster
      shell: source ~/.profile; ./run.sh
      args:  
        chdir: "{{ result_kube_home.stdout }}/crunchy-postgres"
        executable: /bin/bash
      register: result
      delegate_to: "{{groups['kubernetes-kubemasters'].0}}"

    - name: Confirm the postgres statefulset is running 
      shell: source ~/.profile; kubectl get pods | grep pgset
      args:
        executable: /bin/bash
      delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
      register: setup
      until: "'pgset-0' and 'Running' in setup.stdout_lines[0] and 'pgset-1' and 'Running' in setup.stdout_lines[1]"
      delay: 300
      retries: 6

    - name: Verify that the postgres master and replica are available as cluster services
      shell: source ~/.profile; kubectl get svc
      args:
        executable: /bin/bash
      delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
      register: result_service
      failed_when: "'pgset-master' and 'pgset-replica' not in result_service.stdout"

  


