---
- hosts: localhost

  vars_files:
    - k8s-crunchy-pg-vars.yml 

  tasks:

    - name: Get $HOME of K8s master for kubernetes user
      shell: source ~/.profile; echo $HOME
      args:
        executable: /bin/bash
      register: result_kube_home
      delegate_to: "{{groups['kubernetes-kubemasters'].0}}"

    - name: Run the shell script to cleanup postgres cluster
      shell: source ~/.profile; ./cleanup.sh
      args:
        chdir: "{{ result_kube_home.stdout }}/crunchy-postgres"
        executable: /bin/bash
      register: postgres_cleanup
      delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
      ignore_errors: true

    - name: Confirm postgres pods have been deleted
      shell: source ~/.profile; kubectl get pods
      args:
        executable: /bin/bash
      delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
      register: result
      until: "'pgset' not in result.stdout"
      delay: 120 
      retries: 6


   
